job: extension
config:
  name: replace
  process:
  - type: sd_trainer
    training_folder: output
    device: cuda:0
    network:
      type: lora
      linear: 16
      linear_alpha: 16
    save:
      dtype: float16
      max_step_saves_to_keep: 4
      push_to_hub: false
    datasets:
    - folder_path: /content/ai-toolkit/temp/replace
      caption_ext: txt
      caption_dropout_rate: 0.05
      shuffle_tokens: false
      cache_latents_to_disk: false
      resolution:
      - 512
      - 768
      - 1024
    train:
      batch_size: 1
      steps: 1000
      gradient_accumulation_steps: 1
      train_unet: true
      train_text_encoder: false
      gradient_checkpointing: true
      noise_scheduler: flowmatch
      optimizer: adamw8bit
      lr: 0.0004
      ema_config:
        use_ema: true
        ema_decay: 0.99
      dtype: bf16
      skip_first_sample: true
      disable_sampling: true
    model:
      name_or_path: /content/model
      is_flux: true
    trigger_word: replace
meta:
  name: '[name]'
  version: '1.0'